GET http://localhost:3002/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJJbWFtIFJhbWFkaGFuIiwiZW1haWwiOiJpbWFtQGdtYWlsLmNvbSIsImlhdCI6MTY3NTE2NzgxOSwiZXhwIjoxNjc1MTY3ODc5fQ.AwiORwmGVe_G7lBwDmoH93ZiRzjlOWy7B-K3KC0NNMQ

###
POST http://localhost:3002/users
Content-Type: application/json

{
    "name" : "Imam Ramadhan",
    "email" : "imam@gmail.com",
    "password" : "123456",
    "confirmPassword" : "123456"
}

###
POST http://localhost:3002/login
Content-Type: application/json

{
    "email" : "imam@gmail.com",
    "password" : "123456"
}

###
GET http://localhost:3002/token

###
DELETE http://localhost:3002/logout